### ISSUE TITLE
Update Editors in first page and Contributors section

### ISSUE THREAD

**Issue by ounsworth** [EntrustDatacard/draft-ounsworth-lamps-pq-composite-sigs#10]
I would love to be the primary / title author on this, but I am obviously open to discussion and whatever will most help our chances of adoption.

**Comment by csosto-pk** [comment]
@sfluhrer and @csosto-pk are OK with Mike being the primary author. 

If we end up being more than 5 authors I suggest Mike and Max are the Editors that go in the first page and the rest go in a contributors section as it is done in https://tools.ietf.org/html/rfc1122 This is also ducomented in Section 2.12 in https://www.rfc-editor.org/old/instructions2authors.txt

**Comment by ounsworth** [comment]
Cool.
@csosto-pk For the time being, there's nothing to do for this ticket, right? It only becomes an issue once we're more than 5 authors?

**Comment by csosto-pk** [comment]
> Cool.
> @csosto-pk For the time being, there's nothing to do for this ticket, right? It only becomes an issue once we're more than 5 authors?

Yes. We are OK for now. Please keep it so we don't forget if Max P. joins.

**Comment by csosto-pk** [comment]
Now that Max is part of the team we are more than 5. I propose to add Mike O.  and Max P. as the Editors in the draft's first page. And a Contributors section should include the rest of us that are regularly contributing to it. That way the draft does not raise flags with more than 5 authors in the title. 

This is mentioned in multi author in https://www.rfc-editor.org/old/instructions2authors.txt that says 
>2.12 Authors Listed on RFC
>
>      The IESG and IETF have ratified a policy of limiting the number of
>      authors listed in the first page header of an RFC.  The specific
>      policy is as follows:
>
>      (1)  A small set of author names, with affiliations, may appear on
>           the front page header.  These should be the lead author(s)
>           who are most responsible for the actual text.  When there are
>           many contributors, the best choice will be to list the person
>           or (few) persons who acted as document editor(s) (e.g.,"Tom
>           Smith, Editor").
>
>           There is no rigid limit on the size of this set, but there is
>           likely to be a discussion if the set exceeds five authors, in
>           which case the right answer is probably to list one editor.
>
>           The RFC Editor will hold all the people listed on the front
>           page equally responsible for the final form and content of
>           the published RFC.  In particular, the "Author's 48 Hours"
>           final approval period will require signoff from all listed
>           authors.
>
>      (2)  An RFC may include a Contributors section, listing those
>           contributors who deserve significant credit for the document
>           contents.  The Contributors section is intended to provide a
>           level of recognition greater than an acknowledgment and
>           nearly equal to listing on the front page.  The choice of
>           either, both, or none of Contributor and Acknowledgment
>           sections in a particular RFC depends upon the circumstance.

And an example of how it has been done before is in https://tools.ietf.org/html/rfc1122#section-1.4
