### ISSUE TITLE
Inivte Max P. to collaborate

### ISSUE THREAD

**Issue by csosto-pk** [EntrustDatacard/draft-ounsworth-lamps-pq-composite-sigs#24]
Max P. had submitted https://datatracker.ietf.org/doc/draft-pala-composite-crypto/ that touches on CompositeSignatures and Keys. 

We need to invite Max after the -00 version of the draft is submitted.

**Comment by ounsworth** [comment]
Max and Dan have been invited to the call. We need to add them as collaborators in github.

**Comment by csosto-pk** [comment]
Had a call with Max and Dan as part of the team. 
Closing this.
